config/routes.rb
Rails.application.routes.draw do

  root 'calculate_score#index'
  post 'calculate' => 'calculate_score#calculate'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/calculate_score_controller.rb
class CalculateScoreController < ApplicationController
  def index
  end

  def calculate
    bowling_score = BowlingScore.new(params[:score_list])
    if bowling_score.call
      flash[:notice] = "Input: #{params[:score_list]}, total score: #{bowling_score.total_score}"
    else
      flash[:error] = bowling_score.error_message
    end
    redirect_to action: :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/calculate_score/index.html.erb
<h2>Bowling Score</h2>
<%= form_tag calculate_path do %>
  <p>
  <div><%= label_tag :input, 'Please input a string of space separated numbers:' %><div>
  <div><%= text_field_tag :score_list %><div>
  <div><%= submit_tag 'Get Score' %><div>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubyTEst</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: name %>
  <% end %>
  <%= yield %>
</body>
</html>